name: flutter_rave
description: Flutterwave's Rave Card Processing Plugin. Completely supports Android and iOS.
version: 1.0.0
author: Ogbonda Chiziaruhoma
homepage: https://github.com/zfinix/flutter_rave

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  flutter_svg:  0.18.0 
  dio: 3.0.9 
  dio_flutter_transformer: 3.0.2 
  equatable: ^1.1.1
  flushbar: ^1.3.0
  intl: any
  crypto: ^2.0.6
  tripledes: ^2.1.0
  flutter_webview_plugin: ^0.3.5
  url_launcher: ^5.0.2
  webview_flutter: ^0.3.9
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/payments/
    - assets/json/

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
